#!/bin/sh

set -e

get_passwd()
{
  db_get ejabberd/user
  if [ -n "$RET" ]; then
    db_input medium ejabberd/password || true
    db_input medium ejabberd/verify || true
    db_go || true
    db_get ejabberd/password
    PASSWORD="$RET"
    db_get ejabberd/verify
    VERIFY="$RET"
    if [ -z "$PASSWORD" ] || [ "$PASSWORD" != "$VERIFY" ]; then
      db_input medium ejabberd/nomatch || true
      db_go || true
      get_passwd
    fi
  fi
}

get_hostname()
{
  db_input medium ejabberd/hostname || true
  db_go || true

  db_get ejabberd/hostname

  # Convert hostname to lowercase if user entered in uppercase alphabets,
  # save it back to the debconf database, and read it back
  db_set ejabberd/hostname "$(echo "$RET" | sed -e 's/\(.*\)/\L\1/')" && \
	  db_get ejabberd/hostname && \
	  HOST="$RET"

  # Check hostname for invalid characters
  # If there were invalid characters, show error and ask again
  if [ -z "$HOST" ] || echo "$HOST" | grep -Evq '(^[a-z0-9]+$)|^([a-z0-9]*\.)+([a-z0-9]|[a-z0-9][a-z0-9_-]*[a-z0-9]\.)*([a-z0-9]+)$'; then
      db_input medium ejabberd/invalidhostname || true
      db_go || true
      get_hostname
  fi
}

get_username()
{
  db_input medium ejabberd/user || true
  db_go || true
  db_get ejabberd/user

  # If username is not empty, check it for invalid characters
  if [ -n "$RET" ]; then
    # Strip the hostname if user entered it in the JID
    NEWUSER=$(echo "$RET" | sed -e "s/\(.*\)@$HOST/\1/")
    db_set ejabberd/user "$NEWUSER"

    # Check for invalid characters
    if echo "$NEWUSER" | grep -Evq '^[[:alnum:]_\.-]+$'; then
      db_input medium ejabberd/invaliduser || true
      db_go || true
      get_username
    fi
  fi
}

get_credentials()
{
  db_get ejabberd/user
  USER=${RET:-admin}
  db_subst ejabberd/user user "$USER"
  db_get ejabberd/hostname
  HOST=${RET:-hostname}
  db_subst ejabberd/user hostname "$HOST"

  get_username
  get_passwd
}

# Source debconf library.
. /usr/share/debconf/confmodule

get_hostname

FLAG="/var/lib/ejabberd/.admin_registered"
if [ ! -f $FLAG ]; then
  get_credentials
fi

exit 0

